### ISSUE TITLE
Providing a path to the custom plugin in the 'import' field of the allurerc config will throw an error trying to generate a report. This is a regression after upgrading from 3.3.1.

### ISSUE THREAD

**Issue by vlad514** [allure-framework/allure3#598]
The is issue is in https://github.com/allure-framework/allure3/blame/7563796608a2e37d04c570b7f914d8af7b40dd60/packages/core/src/config.ts#L400

const isModuleNotFoundError = (err: unknown): err is Error & { code: "ERR_MODULE_NOT_FOUND" } => {
  return err instanceof Error && "code" in err && err.code === "ERR_MODULE_NOT_FOUND";
};

which checks for "ERR_MODULE_NOT_FOUND" instead of "MODULE_NOT_FOUND" and therefore not proceeding and throwing the error.

**To Reproduce**
1. Add a custom plugin to the allurerc.mjs file, for example:
plugins: {
    "custom-report": {
      import: "/Users/path_to_your_plugin/packages/plugin-awesome/dist/index.js"),
2. Generate a report: npx allure generate
3. Error:
Internal Error: Cannot find module '@allurereport/plugin-/Users/path_to_your_plugin/custom-report/packages/plugin-custom-report/dist/index.js'

**Expected behavior**
A successful generation of the report
